### PR TITLE
ci(check-quotes): 修正权限设定

### PR DESCRIPTION
**Pull request by CCXXXI**
- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。
- https://github.com/OI-wiki/OI-wiki/pull/5329#discussion_r1436228659
- https://github.com/reviewdog/action-suggester/blob/master/README.md#required-permissions

### CODE REVIEW

**Review by Enter-tainer — APPROVED** [review]

**Comment by CCXXXI** [comment]
不 work，权限还是 read：

https://github.com/OI-wiki/OI-wiki/actions/runs/7329421461/job/19959070543?pr=5329#step:1:21

image

可能和这个有关系：

> You can use the permissions key to add and remove read permissions for forked repositories, but typically you can't grant write access. The exception to this behavior is where an admin user has selected the Send write tokens to workflows from pull requests option in the GitHub Actions settings.

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token

**Comment by Enter-tainer** [comment]
@CCXXXI 把write token发到fork里面，安全吗

**Comment by Enter-tainer** [comment]
@Enter-tainer 这里为啥是需要write呢

**Comment by CCXXXI** [comment]
> 把write token发到fork里面，安全吗

不安全，实际上这个选项只在私有库存在

这里提到了一个替代方案：
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

> As an example, as a maintainer you could set up a workflow that takes the artifacts generated by the pull request workflow, do some analysis, and post comments back to the pull request.

这篇回答也提到了这种方案：
https://stackoverflow.com/a/71366152/13805358

**Comment by CCXXXI** [comment]
> @Enter-tainer 这里为啥是需要write呢

根据这篇文档：
https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-pull-requests

`/repos/{owner}/{repo}/pulls/{pull_number}/reviews` 这个接口需要 write 权限

**Comment by Enter-tainer** [comment]
这个check quote不是打log就行了吗，为什么要用这个接口

**Comment by CCXXXI** [comment]
> 这个check quote不是打log就行了吗，为什么要用这个接口

收益在这里讨论过：
- #4934

不过现在看起来做这个的成本比较高，可能退回 #4845 的状态更好？

**Comment by Enter-tainer** [comment]
+1，如果难整的话就revert吧

**Pull request merged**
