### PR TITLE
feat:(base.md):增加16进制相关知识

### PR DESCRIPTION
**Pull request by yanboishere**
- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

### CODE REVIEW

**Comment by Tiphereth-A** [comment]
建议补充来源

**Comment by yanboishere** [comment]
https://zh.wikipedia.org/wiki/十六进制 国内部分讲单片机（比如C51）的教材里也有相关内容

**Comment by alphagocc** [comment]
能否将具体来源部分指明？我只看到了 `令人混淆` 并不意味着 `令机器混淆`

**Comment by Tiphereth-A** [comment]
> https://zh.wikipedia.org/wiki/十六进制

中文版的词条里这个说法也没有来源，而且我没有英文版词条里找到类似表述

**Comment by yanboishere** [comment]
英文版里有这么一条：
[Unix](https://en.wikipedia.org/wiki/*nix) (and related) shells, [AT&T](https://en.wikipedia.org/wiki/AT%26T_Corporation) assembly language and likewise the [C programming language](https://en.wikipedia.org/wiki/C_(programming_language)) (and its syntactic descendants such as [C++](https://en.wikipedia.org/wiki/C%2B%2B), [C#](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)), [Go](https://en.wikipedia.org/wiki/Go_(programming_language)), [D](https://en.wikipedia.org/wiki/D_(programming_language)), [Java](https://en.wikipedia.org/wiki/Java_(programming_language)), [JavaScript](https://en.wikipedia.org/wiki/JavaScript), [Python](https://en.wikipedia.org/wiki/Python_(programming_language)) and [Windows PowerShell](https://en.wikipedia.org/wiki/Windows_PowerShell)) use the prefix 0x for numeric constants represented in hex: 0x5A3

**Comment by Tiphereth-A** [comment]
> 英文版里有这么一条：
> [Unix](https://en.wikipedia.org/wiki/*nix) (and related) shells, [AT&T](https://en.wikipedia.org/wiki/AT%26T_Corporation) assembly language and likewise the [C programming language](https://en.wikipedia.org/wiki/C_(programming_language)) (and its syntactic descendants such as [C++](https://en.wikipedia.org/wiki/C%2B%2B), [C#](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)), [Go](https://en.wikipedia.org/wiki/Go_(programming_language)), [D](https://en.wikipedia.org/wiki/D_(programming_language)), [Java](https://en.wikipedia.org/wiki/Java_(programming_language)), [JavaScript](https://en.wikipedia.org/wiki/JavaScript), [Python](https://en.wikipedia.org/wiki/Python_(programming_language)) and [Windows PowerShell](https://en.wikipedia.org/wiki/Windows_PowerShell)) use the prefix 0x for numeric constants represented in hex: 0x5A3

这句话并没有提到 `让解释器更易辨识到数的存在`

**Comment by Enter-tainer** [comment]
感觉好像没听说过这个说法...目前好像也没有给出可信的出处。先close了，如果之后有update可以再次reopen

**Comment by yanboishere** [comment]
好的

**Comment by yanboishere** [comment]
这一条是我们本专业数字电路课时讲到的，但我现在也没有找到具体的出处，等以后找到再更新。

**Comment by CCXXXI** [comment]
去掉 0 直接以 x 开头的话会难以分辨是数字还是标识符，所以这个说法的正确性应该是比较明显的；不过这种知识感觉有点超出了收录范围？

**Comment by yanboishere** [comment]
🥲

**Pull request closed without merging**
