### PR TITLE
ci(Mergify): introduce Mergify

### PR DESCRIPTION
**Pull request by Enter-tainer**
This change has been made by @Enter-tainer from https://mergify.com config editor.

### CODE REVIEW

**Review by Ir1d — APPROVED** [review]
nbnb

**Review by abc1763613206 — APPROVED** [review]
高级，合上试一试

**Comment by ouuan** [comment]
为啥不用 gh 的 auto-merge

**Comment by ouuan** [comment]
以及为啥这个 bot 这么快就获得大家同意了，我之前说过几次 auto-merge 大家都反对（

**Pull request merged**
