### PR TITLE
feat(intro/faq.md): add gh-check script to get fastest GitHub IP

### PR DESCRIPTION
**Pull request by CoelacanthusHex**
Python Script by lilydjwg: https://gist.github.com/lilydjwg/93d33ed04547e1b9f7a86b64ef2ed058
Introduction by lilydjwg: https://blog.lilydjwg.me/2019/8/16/gh-check.214730.html
Perl Script by hellojukay: https://gist.github.com/lilydjwg/93d33ed04547e1b9f7a86b64ef2ed058#gistcomment-3401138

### CODE REVIEW

**Comment by Enter-tainer** [comment]
可以考虑加上 fastgit.org?

**Comment by CoelacanthusHex** [comment]
> 可以考虑加上 fastgit.org?

确实

**Comment by CoelacanthusHex** [comment]
> 可以考虑加上 fastgit.org?

done

**Review by Enter-tainer — APPROVED** [review]
thx

**Review by StudyingFather — APPROVED** [review]

**Pull request merged**
