### PR TITLE
feat(tool/editor/guide.md): add way to install GUIDE

### PR DESCRIPTION
**Pull request by CoelacanthusHex**
\[1]: https://github.com/OI-wiki/OI-wiki/issues/2664#issuecomment-767561469
[2]: https://github.com/OI-wiki/OI-wiki/pull/2913#discussion_r564797860

left TODO:
- way to install on Fedora (depend on a `checkinstall` package on OBS/Copr for Fedora)

### CODE REVIEW

**Comment by CoelacanthusHex** [comment]
格式化波特似乎不工作了

**Comment by CoelacanthusHex** [comment]
遇上一个问题，代码块里的 Tab 会被渲染成空格
这样的话不符合 Makefile 语法，会很麻烦

**Comment by CoelacanthusHex** [comment]
I try to avoid it by using `echo "xxx\n\txxx"` instead of Heredoc.
but this problem should be fix in the future.

Ref: [`01c9f7f` (#2919)](https://github.com/OI-wiki/OI-wiki/pull/2919/commits/01c9f7fb36448a0ce138810b66508f1fcc5df542)

**Review by Xeonacid — APPROVED** [review]
thx!

**Review by StudyingFather — APPROVED** [review]

**Pull request merged**
