### PR TITLE
快速幂词条的翻译

### LINKED ISSUE #3911: [内容疑似有误] 快速幂词条的翻译
### 请选择：

- [ ] 我正在着手修复这个问题

### 我正在访问这个页面

https://oi-wiki.org/math/quick-pow/

### 我发现页面有这样的问题

https://oi-wiki.org/math/quick-pow/ 采用了 quick-pow 但是外文文献似乎一般称为 fast power algorithm 而非 quick

参考 en.wikipedia 算法竞赛中的快速幂算法实质上对应 exponentiation by squaring，而 binary exponentiation 似乎不是普遍称呼

### PR DESCRIPTION
**Pull request by Great-designer**
fix #3911

### CODE REVIEW

**Comment by Enter-tainer** [comment]
@Great-designer 一些其他的名字：
In mathematics and computer programming, exponentiating by squaring is a general method for fast computation of large positive integer powers of a number, or more generally of an element of a semigroup, like a polynomial or a square matrix. Some variants are commonly referred to as square-and-multiply algorithms or binary exponentiation. These can be of quite general use, for example in modular arithmetic or powering of matrices. For semigroups for which additive notation is commonly used, like elliptic curves used in cryptography, this method is also referred to as double-and-add.

**Comment by Great-designer** [comment]
> In mathematics and computer programming, exponentiating by squaring is a general method for fast computation of large positive integer powers of a number, or more generally of an element of a semigroup, like a polynomial or a square matrix. Some variants are commonly referred to as square-and-multiply algorithms or binary exponentiation. These can be of quite general use, for example in modular arithmetic or powering of matrices. For semigroups for which additive notation is commonly used, like elliptic curves used in cryptography, this method is also referred to as double-and-add.

根据这里的表述，无论quick-power还是fast-power，都不是通用的译名，所以这个改动是不合理的。
合理的译名有：“exponentiating by squaring”、“square-and-multiply algorithms”、“binary exponentiation”。
文中使用的译名是Binary Exponentiation。
所以，页面地址命名为什么比较好？

**Comment by Great-designer** [comment]
*，这都能出现红叉标记……（捂脸）

**Comment by Enter-tainer** [comment]
> *，这都能出现红叉标记……（捂脸）

可能是因为没改 mkdocs.yml ?

**Review by Enter-tainer — APPROVED** [review]
thx！

**Pull request merged**
